# -*- mode: ruby -*-
# # vi: set ft=ruby :

require 'fileutils'
Vagrant.require_version ">= 1.6.0"

$instance_name="node-%01d"
$instance_ip="10.10.10.1%01d"
$num_instances=2

$box = "fedora/23-cloud-base"

$virtualbox_gui = false
$virtualbox_memory = 768
$virtualbox_cpus = 1

Vagrant.configure("2") do |config|
    config.vm.box = $box

    (1..$num_instances).each do |i|
        config.vm.define vm_name = $instance_name % i do |config|
            config.vm.hostname = vm_name
            config.vm.network :private_network, ip: $instance_ip % i, autoconfig: false
            config.vm.provider :virtualbox do |virtualbox|
                virtualbox.gui = $virtualbox_gui
                virtualbox.memory = $virtualbox_memory
                virtualbox.cpus = $virtualbox_cpus
            end

            # sync files
            config.vm.provision "file", source: "PubSubExampleBundle.jar", destination: "/home/vagrant/demo.jar"
            config.vm.provision "file", source: "jdk", destination: "/home/vagrant/jdk"
            config.vm.provision :shell, :path => "startup.sh", run: "always", privileged: false
            config.vm.synced_folder ".", "/vagrant", disabled: true
        end
    end
end
